# Generated by Django 4.2.1 on 2023-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="difficulty",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(max_length=255),
        ),
    ]
